language: node_js
sudo: false

os: linux

env:
  global:
    - NODE_VERSION=10

before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm@6 && node -v && npm -v

install:
  - npm ci

script:
  - npm run build
  - npm test

deploy:
  provider: npm
  email: "tomas.dostal@kpsys.cz"
  api_key: $NPM_TOKEN
  skip_cleanup: true
